server:
  port: ":8088"
  ip: "localhost"

database:
  addr: "47.93.22.146"
  port: "3306"
  user: "dms"
  pass: "lcx-machine0918LMY"
  name: "manidb"

client:
  user: ":8088"
  center: ":8089"
  engine: ":8087"